CREATE DATABASE IF NOT EXISTS budiak;

USE budiak;

DROP TABLE Record;

ALTER TABLE users MODIFY COLUMN pass VARCHAR(250);

CREATE TABLE IF NOT EXISTS Users (
   id INT PRIMARY KEY AUTO_INCREMENT,
   username VARCHAR(50),
   pass VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS Categories (
   id INT PRIMARY KEY AUTO_INCREMENT,
	cat_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Places (
   id INT PRIMARY KEY AUTO_INCREMENT,
	place VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Record (
	id INT PRIMARY KEY AUTO_INCREMENT,
	val DECIMAL(10, 2) NOT NULL,
   user_id INT NOT NULL,
	category INT NOT NULL,
   place INT NOT NULL,
   caption TEXT NOT NULL,
   _date DATE NOT NULL,
   FOREIGN KEY (category) REFERENCES Categories(id) ON DELETE CASCADE,
   FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
   FOREIGN KEY (place) REFERENCES Places(id) ON DELETE CASCADE	
);
